matrix:
- name: Markdown files
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - doc/.sphinx/.wordlist.txt
    output: doc/.sphinx/.wordlist.dic
  sources:
  - doc/html/**/*.html|!doc/html/config-options/index.html
  pipeline:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - code
      - pre
      - spellexception
      - link
      - title
      - div.relatedlinks
      - span.guilabel
      - a.p-navigation__link
