name: Tests
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:

  documentation-checks:
    uses: ru-fu/documentation-workflows/.github/workflows/documentation-checks.yaml@make-targets-configurable
    with:
      working-directory: './doc'
      makefile: 'Makefile'
      pa11y-target: 'help'
