name: Triaging
on:
- pull_request_target

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    name: PR labels
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
  notify:
    name: Notify
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: iamfj/action-label-notification@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mapping: >
            - label: Documentation
              recipients:
                - '@ru-fu'
